%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
CameraMat: !!opencv-matrix
  rows: 3
  cols: 3
  dt: d
  data: [561.69515709749,     0.0,      512,
         0.0,     421.2713678231175,      384,
         0.0,     0.0,      1.0     ]

DistCoeffs: !!opencv-matrix
  rows: 5
  cols: 1
  dt: d
  data: [0.0, 0.0, 0.0, 0.0, 0.000000]

Camera.width: 1024
Camera.height: 768
