%YAML:1.0

# Topic name in rosbag
PointCloudTopic: "/rslidar_points"
ImageTopic: "/usb_cam/image_raw"

# Lidar Data type(custom msg or pointcloud2)
Data.custom_msg: 0
# Initial extrinsic (usually provided by hand measurement or cad design)

ExtrinsicMat: !!opencv-matrix
  rows: 4
  cols: 4
  dt: d
#  data: [0.0,   -1.0,   0.0,    0.0,
#         0.0,  0.0,  -1.0,    0.0,
#         1.0,   0.0,    0.0,    0.0,
#         0.0,   0.0,    0.0,    1.0]
  data: [ 8.7242893694914735e-03, -9.9970454218751792e-01,
          -2.2687333572781358e-02, 0., -7.6913505221610820e-02,
          2.1950115738959532e-02, -9.9679612014371910e-01,
          5.9999999999999998e-02, 9.9699959854030162e-01,
          1.0441300143734738e-02, -7.6699281364207200e-02, 0., 0., 0., 0.,
          1. ]
# Params for Canny Edge Extraction

Canny.gray_threshold: 10
Canny.len_threshold: 200

# Params for Voxel Cutting & Plane Fitting & Edge Extraction
Voxel.size: 0.5
Voxel.down_sample_size: 0.02
Plane.min_points_size: 30
Plane.normal_theta_min: 30
Plane.normal_theta_max: 145
Plane.max_size: 8
Ransac.dis_threshold: 0.02
Edge.min_dis_threshold: 0.03
Edge.max_dis_threshold: 0.06
AdjustEuler1: -2
AdjustEuler2: -0.5
AdjustEuler3: 2

# Params for color point clouds
Color.dense: 0.1
Color.intensity_threshold: 5
